#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "staging"

python /app/manage.py collectstatic --noinput
python manage.py loaddata orderbook_veinte/utils/seeders/order_status.json
python manage.py migrate

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app
