version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: orderbook_veinte_local_django
    depends_on:
      - postgres
      - mailhog
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  
  
  golang:
    build : 
      context: . 
      dockerfile: ./compose/local/golang/Dockerfile
    image: orderbook_veinte_local_golang
    depends_on:
      - django
      - redis 
    volumes : 
      - .:/app
    ports:
      - "8001:8001"
    command: ./app


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: orderbook_veinte_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    ports : 
      - "6379:6379"

  celeryworker:
    <<: *django
    image: orderbook_veinte_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: orderbook_veinte_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: orderbook_veinte_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
