# Generated by Django 3.0.5 on 2020-05-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uptadeted_at', models.DateTimeField(null=True)),
                ('orderId', models.AutoField(help_text='id of the Trade auto increment field', primary_key=True, serialize=False)),
                ('traderId', models.CharField(max_length=255)),
                ('timestamp', models.TimeField()),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('Bid', models.BooleanField(default=False)),
                ('Ask', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uptadeted_at', models.DateTimeField(null=True)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('timestamp', models.TimeField()),
                ('p1_traderId', models.CharField(max_length=255)),
                ('p1_side', models.CharField(max_length=255)),
                ('p1_orderId', models.CharField(max_length=255)),
                ('p2_traderId', models.CharField(max_length=255)),
                ('p2_side', models.CharField(max_length=255)),
                ('p2_orderId', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uptadeted_at', models.DateTimeField(null=True)),
                ('type_transaction', models.CharField(choices=[('partial', 'complete')], max_length=120)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_buyer', to='orderbook.Orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_seller', to='orderbook.Orders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
