# Generated by Django 3.0.5 on 2020-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uptadeted_at', models.DateTimeField(null=True)),
                ('orderId', models.AutoField(help_text='id of the Trade auto increment field', primary_key=True, serialize=False)),
                ('traderId', models.CharField(max_length=255)),
                ('timestamp', models.TimeField()),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('Bid', models.BooleanField(default=False)),
                ('Ask', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uptadeted_at', models.DateTimeField(null=True)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('timestamp', models.TimeField()),
                ('p1_traderId', models.CharField(max_length=255)),
                ('p1_side', models.CharField(max_length=255)),
                ('p1_orderId', models.CharField(max_length=255)),
                ('p2_traderId', models.CharField(max_length=255)),
                ('p2_side', models.CharField(max_length=255)),
                ('p2_orderId', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
