# Generated by Django 3.0.5 on 2020-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='qty_total',
            field=models.IntegerField(default=0),
        ),
    ]
