# Generated by Django 3.0.5 on 2020-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='hash_order',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
